server:
  port: ${PORT:1988}

logging:
  level:
    com:
      agathium:
        common: debug

mongodb:
  database: ${DB:agathium_applications_data}
  hosts:
    -
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
#    -
#      host: localhost
#      port: 27018

spring:
  data:
    mongodb:
      database: ${DB:agathium_applications_data}
      repositories:
        type: AUTO
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}